elkx:
  image: sebp/elkx
  ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"
  environment:
    - ELASTICSEARCH_USER=test
    - ELASTICSEARCH_PASSWORD=test
    - KIBANA_USER=test
    - KIBANA_PASSWORD=test
